# 1. Database Configuration (Different DB Name)
spring.datasource.url=jdbc:mysql://localhost:3306/product_inventory_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=shraddha20

# 2. Server Port (Different from Student Project)
# Use 8081 so it doesn't conflict with Student (8093)
server.port=8081

# 3. Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. JSON Format (Optional but helpful for Inventory)
spring.jackson.serialization.indent_output=true